HET/apps/front/forms.py
from wtforms import StringField,IntegerField,FileField
from ..forms import BaseForm
from wtforms.validators import Regexp,EqualTo,ValidationError,InputRequired
from utils import hetcache
from flask_wtf.file import FileRequired,FileAllowed


class SignupForm(BaseForm):
    telephone = StringField(validators=[Regexp(r'1[345789]\d{9}',message='请输入正确格式的手机号码')])
    sms_captcha = StringField(validators=[Regexp(r"\w{4}",message='请输入正确格式的短信验证码')])
    username = StringField(validators=[Regexp(r'.{2,20}',message='请输入正确格式的用户名')])
    password1 = StringField(validators=[Regexp(r'[0-9a-zA-Z_\.]{6,20}',message='请输入正确格式的密码！')])
    password2 = StringField(validators=[EqualTo('password1',message='两次输入的密码不一致！')])
    graph_captcha = StringField(validators=[Regexp(r'\w{4}',message='请输入正确格式的图形验证码')])

    def validate_sms_captcha(self,field):
        sms_captcha = field.data
        telephone = self.telephone.data

        sms_captcha_mem = hetcache.get(telephone)
        if not sms_captcha_mem or sms_captcha_mem.lower() != sms_captcha.lower():
            raise ValidationError(message='短信验证码错误！')


    def validate_graph_chaptcha(self,field):
        graph_captcha = field.data

        graph_captcha_mem = hetcache.get(graph_captcha.lower())
        if not graph_captcha_mem:
            raise ValidationError(message='图形验证错误！')


class SigninForm(BaseForm):
    telephone = StringField(validators=[Regexp(r'1[345789]\d{9}', message='请输入正确格式的手机号码')])
    password = StringField(validators=[Regexp(r'[0-9a-zA-Z_\.]{6,20}', message='请输入正确格式的密码！')])
    remeber = StringField()


class ForgotpwdForm(BaseForm):
    telephone = StringField(validators=[Regexp(r'1[345789]\d{9}', message='请输入正确格式的手机号码')])
    sms_captcha = StringField(validators=[Regexp(r"\w{4}", message='请输入正确格式的短信验证码')])

    def validate_sms_captcha(self,field):
        sms_captcha = field.data
        telephone = self.telephone.data

        sms_captcha_mem = hetcache.get(telephone)
        if not sms_captcha_mem or sms_captcha_mem.lower() != sms_captcha.lower():
            raise ValidationError(message='短信验证码错误！')


class UpdatepwdForm(BaseForm):
    password1 = StringField(validators=[Regexp(r'[0-9a-zA-Z_\.]{6,20}', message='请输入正确格式的密码！')])
    password2 = StringField(validators=[EqualTo('password1', message='两次输入的密码不一致！')])


class AddPostForm(BaseForm):
    title = StringField(validators=[InputRequired(message='请输入标题！')])
    content = StringField(validators=[InputRequired(message='请输入内容！')])
    board_id = IntegerField(validators=[InputRequired(message='请输入板块id')])


class AddCommentForm(BaseForm):
    content = StringField(validators=[InputRequired(message='请输入评论内容！')])
    post_id = IntegerField(validators=[InputRequired(message='请输入帖子id')])


class UploadForm(BaseForm):
    avator = FileField(validators=[FileRequired(),FileAllowed(['jpg','png','saz','gif'])])
    desc = StringField(validators=[InputRequired()])

class AddProjectForm(BaseForm):
    app_id = StringField(validators=[InputRequired(message='请输入项目的appid')])
    name = StringField(validators=[InputRequired(message='请输入项目的名字')])
    interface_name = StringField(validators=[InputRequired(message='请输入接口的名字')])
    interface_url = StringField(validators=[InputRequired(message='请输入接口的url')])
    parameter_key = StringField(validators=[InputRequired(message='请输入接口参数的key')])
    parameter_value = StringField(validators=[InputRequired(message='请输入接口参数的value')])
    typed = StringField(validators=[InputRequired(message='请输入请求类型')])
    method = StringField(validators=[InputRequired(message='请输入请求方法')])
    sign = StringField(validators=[InputRequired(message='请输入是否需要签名')])
    domain = StringField(validators=[InputRequired(message='请输入接口域名')])
    have_headers = StringField(validators=[InputRequired(message='请输入是否需要请求头')])
    expected_code = StringField(validators=[InputRequired(message='请输入期望值')])

HET/apps/common/views.py
from flask import Blueprint,request,make_response,jsonify
from exts import alidayu
from utils import restful,hetcache
from utils.captcha import Captcha
from .forms import SMSCaptchaForm
from io import BytesIO
import qiniu
from tasks import send_sms_captcha

bp = Blueprint('common',__name__,url_prefix='/c')


@bp.route('/')
def index():
    return 'common index'

# @bp.route('/sms_captcha/')
# def sms_captcha():
#     telephone = request.args.get('telephone')
#     if not telephone:
#         return restful.params_error(message='请传入手机号码')
#     captcha = Captcha.gene_text(number=4)
#     if alidayu.send_sms(telephone,code=captcha):
#         return restful.success()
#     else:
#         return restful.params_error(message='短信验证码发送失败！')

@bp.route('/sms_captcha/',methods=['POST'])
def sms_captcha():
    form = SMSCaptchaForm(request.form)
    if form.validate():
        telephone = form.telephone.data
        captcha = Captcha.gene_text(number=4)
        print('发送的短信验证码是：', captcha)
        # if alidayu.send_sms(telephone, code=captcha):
        #     hetcache.set(telephone,captcha)
        #     return restful.success()
        # else:
        #     return restful.params_error(message='短信验证码发送失败！')
        #     # hetcache.set(telephone, captcha)
        #     # return restful.success()
        hetcache.set(telephone, captcha)
        send_sms_captcha(telephone,captcha)
        return restful.success()
    else:
        return restful.params_error(message='参数错误！')


@bp.route('/captcha/')
def graph_captcha():
    # 获取验证码
    text,image = Captcha.gene_graph_captcha()
    hetcache.set(text.lower(),text.lower())
    out = BytesIO()
    image.save(out,'png')
    out.seek(0)
    resp = make_response(out.read())
    resp.content_type = 'image/png'
    return resp


@bp.route('/uptoken/')
def uptoken():
    access_key = 'tJLW2rNi_r60-2S_G2urRFzwg74lBarak-U4k9EE'#'M4zCEW4f9XPanbMN-Lb9O0S8j893f0e1ezAohFVL'
    secret_key = 'nVGDI0vihLlEbRQU6EoUz1thNi491aSH0_wS6iMa'#'7BKV7HeEKM3NDJk8_l_C89JI3SMmeUlAIatzl9d4'
    q = qiniu.Auth(access_key,secret_key)

    bucket = 'denger'#'hyvideo'
    token = q.upload_token(bucket)
    return jsonify({'uptoken':token})

HET/apps/front/views.py
from flask import (Blueprint,
                   views,
                   render_template,
                   request,
                   session,
                   url_for,
                    g,
                    abort,
                    send_from_directory
                   )
from .forms import SignupForm,SigninForm,AddPostForm,AddCommentForm,AddProjectForm,ForgotpwdForm,UpdatepwdForm,UploadForm
from utils import restful,safeutils,hetcache
from .models import FrontUser,InputInterface,UploadFileForm
from ..models import BannerModel,BoardModel,PostModel,CommentModel,HighlightPostModel,ReadcountModel
from exts import db
import config,time
from .decorators import login_required
from flask_paginate import Pagination,get_page_parameter
from sqlalchemy.sql import func
import re
import os
from werkzeug.utils import secure_filename
from utils.het_fiddler.main import main
from werkzeug.datastructures import CombinedMultiDict



bp = Blueprint('front',__name__)


@bp.route('/')
def index():
    board_id = request.args.get('bd',type=int,default=None)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    sort = request.args.get('st',type=int,default=1)
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(4)
    boards = BoardModel.query.all()
    start = (page-1)*config.PER_PAGE
    end = start + config.PER_PAGE
    posts = None
    total = 0
    query_obj = None
    if sort == 1:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        # 按照加精的时间倒序排序
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).\
            order_by(HighlightPostModel.create_time.desc(),PostModel.create_time.desc())
    elif sort == 3:
        # 按照阅读的数量排序
        # query_obj = PostModel.query.order_by(func.count(ReadcountModel.counts).desc(),PostModel.create_time)
        query_obj = db.session.query(PostModel).outerjoin(ReadcountModel).group_by(PostModel.id).\
                    order_by(func.count(ReadcountModel.counts).desc(),PostModel.create_time)

    elif sort == 4:
        # 按照评论数量排序
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).\
            group_by(PostModel.id).order_by(func.count(CommentModel.id).desc(),PostModel.create_time)


    if board_id:
            query_obj = query_obj.filter(PostModel.board_id== board_id)
            posts = query_obj.slice(start,end)
            total = query_obj.count()

    else:

        posts = query_obj.slice(start,end)
        query_obj.count()

    #
    # print('帖子总数是%s'%total)
    # print('当前是第：%s页'%page)
    count = 0
    read_counts = {}
    answer_counts = {}

    for post in posts:
        read_obj = ReadcountModel.query.filter(ReadcountModel.post_id == post.id).first()
        if not read_obj:
            read_count = 1
        else:
            read_count = read_obj.counts + 1
        answer_count = len(CommentModel.query.filter(CommentModel.post_id == post.id).all())
        answer_counts[post.id] = answer_count
        read_counts[post.id] = read_count
    pagination = Pagination(bs_version=3,page=page,total=total,outer_window=0,inner_window=2)
    context = {
        'banners':banners,
        'boards':boards,
        'posts':posts,
        'pagination':pagination,
        'current_board':board_id,
        'current_sort':sort,
        'answer_counts':answer_counts,
        'read_counts':read_counts

    }
    count += 1
    return render_template('front/front_index.html',**context)


@bp.route('/p/<post_id>/')
@login_required
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    counts = ReadcountModel.query.filter(ReadcountModel.post_id == post_id).first()
    reads = 0
    if counts:
        reads = counts.counts + 1
        counts.counts += 1
        counts.post_id,counts.counts,counts.post = post_id,reads,post
    else:
        reads = 1
        counts = ReadcountModel(post_id=post.id, counts=reads)
        counts.post = post

    db.session.add(counts)
    db.session.commit()
    if not post:
        abort(404)
    answer_count = len(CommentModel.query.filter(CommentModel.post_id == post_id).all())
    return render_template('front/front_pdetail.html',post=post,answer_count=answer_count,reads=reads)


@bp.route('/aproject/',methods=['POST'])
@login_required
def add_project():
    form = AddProjectForm(request.form)
    if form.validate():
        app_id = form.app_id.data
        name = form.name.data
        interface_name = form.interface_name.data
        interface_url = form.interface_url.data
        parameter_key = form.parameter_key.data
        parameter_value =form.parameter_value.data
        typed = form.typed.data
        methods = form.method.data
        sign = form.sign.data
        domain = form.domain.data
        have_headers = form.have_headers.data
        expected_code = form.expected_code.data
        timestamp = str(int(time.time())*1000)[:13]

        newinterface = InputInterface(app_id=app_id,name=name,interface_name=interface_name,interface_url=interface_url,
                                    parameter_key=parameter_key,parameter_value=parameter_value,typed=typed,methods=methods,
                                    sign=sign,domain=domain,have_headers=have_headers,expected_code=expected_code,
                                      timestamp=timestamp)
        newinterface.author_id = g.front_user.id
        db.session.add(newinterface)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())



@bp.route('/acomment/',methods=['POST'])
@login_required
def add_comment():
    form = AddCommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.add(comment)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message='评论的帖子不存在！')
    else:
        return restful.params_error(message=form.get_error())

@bp.route('/apost/',methods=['GET','POST'])
@login_required
def apost():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/front_apost.html',boards=boards)
    else:
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
                return restful.params_error(message='没有这个板块！')
            post = PostModel(title=title,content=content,board_id=board_id)
            post.board = board
            post.author = g.front_user
            db.session.add(post)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())



@bp.route('/upload/',methods=['GET','POST'])
@login_required
def upload():
    if request.method == 'GET':
        return render_template('front/front_upload.html')
    else:
        form = UploadForm(CombinedMultiDict([request.form,request.files]))
        if form.validate():
            desc = request.form.get('desc','这个人很懒，什么都没有留下！')
            avator = request.files.get('avator')
            filename = secure_filename(avator.filename)
            timestamp = str(int(time.time())*1000)[:13]
            filename = timestamp + '_' + filename
            UPLOAD_PATH = os.path.join(os.getcwd(), 'utils/het_fiddler/datas/saz/')
            avator.save(os.path.join(UPLOAD_PATH, filename))
            exists_file = UploadFileForm.query.filter_by(author_id=g.front_user.id).first()
            if exists_file:
                exists_file.file_url=UPLOAD_PATH
                exists_file.file_name = filename
            else:
                _upload = UploadFileForm(desc=desc,file_url=UPLOAD_PATH,file_name=filename)
                _upload.author = g.front_user
                db.session.add(_upload)
            db.session.commit()
            return restful.success(message='文件上传成功！')
        else:
            return restful.params_error(message=form.get_error())

@bp.route('/excute/',methods=['GET','POST'])
@login_required
def excute():
    if request.method == 'GET':
        path = UploadFileForm.query.filter_by(author_id=g.front_user.id).first().file_name
        return render_template('front/front_excute.html',path=path)
    else:
        find_obj = UploadFileForm.query.filter_by(author_id=g.front_user.id).first()
        case_name = find_obj.file_name
        main(case_name)
        return restful.success()




@bp.route('/images/<filename>/')
@login_required
def get_image(filename):
    return send_from_directory(UPLOAD_PATH,filename)



class UpdatepwdView(views.MethodView):
    def get(self):
        return render_template('front/front_updatepwd.html')

    def post(self):
        form = UpdatepwdForm(request.form)
        if form.validate():
            password = form.password1.data
            telephone = updatepwd_telephone
            user = FrontUser.query.filter_by(telephone=telephone).first()
            user.password = password
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())


class ForgotpwdView(views.MethodView):
    def get(self):
        return render_template('front/front_forgotpwd.html')

    def post(self):
        form = ForgotpwdForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            query_telephone = FrontUser.query.filter_by(telephone=telephone).first()
            if not query_telephone:

HET/templates/front/front_apost.html
{% extends 'front/front_base.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}
项目接口录入
{% endblock %}

{% block head %}
    <script src="{{ static('ueditor/ueditor.config.js') }}"></script>
    <script src="{{ static('ueditor/ueditor.all.min.js') }}"></script>
    <script src="{{ static('front/js/front_apost.js') }}"></script>
{% endblock %}

{% block body %}
<form action="" method="post">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">标题</span>
            <input type="text" class="form-control" name="title">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">板块</span>
            <select name="board_id" class="form-control">
                {% for board in boards %}
                    <option value="{{ board.id }}">{{ board.name }}</option>
                {% endfor %}

            </select>
        </div>
    </div>
    <div class="form-group">
        <script id="editor" type="text/plain" style="height:500px;"></script>
    </div>
    <div class="form-group">
        <button class="btn btn-danger" id="submit-btn">发布文章</button>
    </div>
</form>
{% endblock %}

HET/templates/front/front_excute.html
{% extends 'front/front_signbase.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}
文件执行
{% endblock %}

{% block head %}
    <script src="{{ static('front/js/front_excute.js') }}"></script>
{% endblock %}

{% block h2_block %}
{{ self.title() }}
{% endblock %}

{% block signbox %}
   <div class="form-group">
       <div class="input-group">
           <form action="" method="post" enctype="multipart/form-data">
                <table>
                    <tbody>
                        <tr>
                            <td>saz文件</td>
                            <td><input type="text" style="width:300px;" name="avator" value="{{ path }}"></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>
                                <div class="form-group">
                                   <button class="btn btn-warning btn-block" id="excute-btn">
                                       立即执行
                                   </button>

                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </form>

       </div>
   </div>

{% endblock %}

HET/templates/front/front_index.html
{% extends 'front/front_base.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}
HET接口测试
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ static('front/css/front_index.css') }}">
    <script src="{{ static('front/js/front_aproject.js') }}"></script>
{% endblock %}

{% block body %}
    <div class="lg-container">
                <div id="carousel-example-generic" class="carousel slide index-banner" data-ride="carousel">
          <!-- Indicators 指示器 -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
          </ol>

          <!-- Wrapper for slides  轮播图-->
          <div class="carousel-inner" role="listbox">
              {% for banner in  banners %}
                  {% if loop.first %}
                    <div class="item active">
                  {% else %}
                      <div class="item">
                  {% endif %}

                    <a href="{{ banner.link_url }}">
                        <img src="{{ banner.image_url }}" alt="...">
                    </a>
            </div>
              
              {% endfor %}
              


          </div>

          <!-- Controls 控制-->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="post-group">
            <ul class="post-group-head">
                {% if current_sort == 1 %}
                    <li class="active"><a href="{{ url_for('front.index',st=1,bd=current_board) }}">最新</a></li>
                {% else %}
                    <li ><a href="{{ url_for('front.index',st=1,bd=current_board) }}">最新</a></li>
                {% endif %}

                {% if current_sort == 2 %}
                    <li class="active"><a href="{{ url_for('front.index',st=2,bd=current_board) }}">版主推荐</a></li>
                {% else %}
                    <li ><a href="{{ url_for('front.index',st=2,bd=current_board) }}">版主推荐</a></li>
                {% endif %}

                {% if current_sort == 3 %}
                    <li class="active"><a href="{{ url_for('front.index',st=3,bd=current_board) }}">阅读最多</a></li>
                {% else %}
                    <li ><a href="{{ url_for('front.index',st=3,bd=current_board) }}">阅读最多</a></li>
                {% endif %}

                {% if current_sort == 4 %}
                    <li class="active"><a href="{{ url_for('front.index',st=4,bd=current_board) }}">评论最多</a></li>
                {% else %}
                    <li ><a href="{{ url_for('front.index',st=4,bd=current_board) }}">评论最多</a></li>
                {% endif %}
{##}
{#                {% if current_sort == 5 %}#}
{#                    <li class="active"><a href="{{ url_for('front.index',st=5,bd=current_board) }}">项目接口</a></li>#}
{#                {% else %}#}
{#                    <li ><a href="{{ url_for('front.index',st=5,bd=current_board) }}">项目接口</a></li>#}
{#                {% endif %}#}

            </ul>
            <div class="post-list-group">
                <ul class="post-list-ul">
                    {% for post in posts %}
                        <li>
                            <div class="author-avatar-group">
                                <img src="{{ post.author.avator or url_for('static',filename='common/images/logo.png') }}" alt="">
                            </div>
                            <div class="post-info-group">
                                <p class="post-title">
                                    <a href="{{ url_for('front.post_detail',post_id=post.id) }}">
                                    {{ post.title }}
                                    </a>
                                    {% if post.highlight %}
                                        <span class="label label-danger">精华文章</span>

                                    {% endif %}
                                </p>
                                <p class="post-info">
                                    <span>作者：{{ post.author.username }}</span>
                                    <span>发表时间：{{ post.create_time }}</span>
                                    <span> 评论：{{ answer_counts[post.id] }}</span>
                                    <span> 阅读：{{ read_counts[post.id] }}</span>
                                </p>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                <div class="page-group" style="text-align: center;">
                    {{ pagination.links}}
                </div>
            </div>
        </div>
    </div>

    <div class="sm-container">
        <div style="padding-bottom:10px;">
            <a href="{{ url_for('front.apost') }}" class="btn btn-warning btn-block">分享文章</a>
        </div>

        <div style="padding-bottom:10px;">
            <button  class="btn btn-warning btn-block" data-toggle="modal" data-target="#project-dialog">项目接口录入</button>
        </div>

        <div style="padding-bottom:10px;">
            <a href="#" class="btn btn-warning btn-block" target="_blank">查看项目接口</a>
        </div>
        <div style="padding-bottom:10px;">
            <a href="{{ url_for('front.upload') }}" class="btn btn-warning btn-block" target="_blank">上传文件</a>
        </div>

        <div class="list-group">
            {% if current_board %}
                <a href="/" class="list-group-item">所有板块</a>
            {% else %}
                <a href="/" class="list-group-item active">所有板块</a>
            {% endif %}

          {% for board in boards %}
              {% if board.id == current_board %}
                  <a href="{{ url_for("front.index",bd = board.id) }}" class="list-group-item active">{{ board.name }}</a>
              {% else %}
                  <a href="{{ url_for("front.index",bd = board.id) }}" class="list-group-item">{{ board.name }}</a>
              {% endif %}
          {% endfor %}

        </div>
    </div>


 <!-- Modal -->
<div class="modal fade" id="project-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">添加项目接口</h4>
      </div>
      <div class="modal-body">
          <form action="" class="form-horizontal">
              <div class="form-group">
                  <label class="col-sm-2 control-label">项目的appid：</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="app_id" placeholder="项目appid">
                  </div>
              </div>

              <div class="form-group">
                  <label class="col-sm-2 control-label">项目名称：</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="name" placeholder="项目名称">
                  </div>
              </div>

              <div class="form-group">
                  <label class="col-sm-2 control-label">接口名称：</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="interface_name" placeholder="接口名称">
                  </div>
              </div>
              <div class="form-group">
                  <label class="col-sm-2 control-label">接口的url：</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="interface_url" placeholder="接口的url">
                  </div>
              </div>

              <div class="form-group">
                  <label class="col-sm-2 control-label">接口参数的key：</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="parameter_key" placeholder="接口参数的key">
                  </div>
              </div>

              <div class="form-group">
                  <label class="col-sm-2 control-label">接口参数的value：</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="parameter_value" placeholder="接口参数的value">
                  </div>
              </div>

              <div class="form-group">
                  <label class="col-sm-2 control-label">接口请求类型：</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="typed" placeholder="接口请求类型(http/https)">
                  </div>
              </div>

              <div class="form-group">
                  <label class="col-sm-2 control-label">接口请求方法：</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="method" placeholder="接口请求方法(POST/GET/ws)">
                  </div>
              </div>

              <div class="form-group">
                  <label class="col-sm-2 control-label">期望返回值：</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="expected_code" placeholder="期望返回值(code=0)">
                  </div>
              </div>

              <div class="form-group">
                  <label class="col-sm-2 control-label">是否签名：</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="sign" placeholder="签名(1:需要，0:不需要)">
                  </div>
              </div>

              <div class="form-group">
                  <label class="col-sm-2 control-label">域名：</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="domain" placeholder="域名">
                  </div>
              </div>

              <div class="form-group">
                  <label class="col-sm-2 control-label">请求头：</label>
                  <div class="col-sm-10">
                      <input type="number" class="form-control" name="have_headers" placeholder="0:有，1:没有">
                  </div>
              </div>

          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="button" class="btn btn-primary" id="save-project-btn">保存</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

HET/templates/front/front_signup.html
{% extends 'front/front_signbase.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}
和而泰tester注册！
{% endblock %}

{% block head %}
<script src="{{ static('front/js/front_signup.js') }}"></script>

{% endblock %}

{% block h2_block %}
{{ self.title() }}
{% endblock %}

{% block signbox %}
<div class="form-group">
       <div class="input-group">
           <input type="text" class="form-control" name="telephone" placeholder="手机号码">
           <span class="input-group-btn">
               <button id="sms-captcha-btn" class="btn btn-default">发送验证码</button>
           </span>
       </div>
   </div>
   <div class="form-group">
       <div class="input-group">
           <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
       </div>
   </div>
   <div class="form-group">
       <div class="input-group">
           <input type="text" class="form-control" name="username" placeholder="用户名">
       </div>
   </div>
   <div class="form-group">
       <div class="input-group">
           <input type="password" class="form-control" name="password1" placeholder="密码">
       </div>
   </div>
   <div class="form-group">
       <div class="input-group">
           <input type="password" class="form-control" name="password2" placeholder="确认密码">
       </div>
   </div>
   <div class="form-group">
       <div class="input-group">
           <input type="text" class="form-control" name="graph_captcha" placeholder="图形验证码">
           <span class="input-group-addon captcha-addon">
               <img class="captcha-img" id="captcha-img" src="{{ url_for('common.graph_captcha') }}" alt="">
           </span>

       </div>
   </div>
   <div class="form-group">
       <button class="btn btn-warning" id="submit-btn">
           立即注册
       </button>
       <a href="{{ url_for('front.signin')}}" style="float:right;margin-top: 14px;" >返回登录</a>
   </div>
{% endblock %}