HET/apps/cms/views.py
from flask import Blueprint,views,render_template,request,session,redirect,url_for,g,jsonify
from .forms import LoginForm,ResetpwdForm,ResetEmailForm,AddBannerForm,UpdateBannerForm,AddBoardForm,UpdateBoardForm
from .models import CMSUser,CMSPersmisson
from .decorators import login_required,permission_required
from ..models import BannerModel,BoardModel,PostModel,HighlightPostModel,ReadcountModel,CommentModel
import config
from exts import db,mail
from utils import restful,hetcache
from flask_mail import Message
import string
import random
from tasks import send_mail

bp = Blueprint('cms',__name__,url_prefix='/cms')


@bp.route('/')
@login_required
def index():
    return render_template('cms/cms_index.html')


@bp.route('/profile/')
@login_required
def profile():
    return render_template('cms/cms_profile.html')


@bp.route('/loginout/')
@login_required
def loginout():
    del session[config.CMS_USER_ID] #session.clear()
    return redirect(url_for('cms.login'))


@bp.route('/email_captcha/')
def email_captcha():
    email = request.args.get('email')
    if not email:
        return restful.params_error('请传递邮箱参数！')
    source = list(string.ascii_letters)
    source.extend(map(lambda x :str(x),range(10)))
    captcha = ''.join(random.sample(source,6))  #返回的是列表
    # message = Message('python后台邮箱验证码',recipients=[email],body='您的验证码是：%s'%captcha)
    #
    # try:
    #     mail.send(message)
    # except:
    #     return restful.server_error()
    send_mail.delay('python后台邮箱验证码', [email], '您的验证码是：%s' % captcha)
    hetcache.set(email,captcha)

    return restful.success()



@bp.route('/email/')
def send_email():
    message = Message('测试邮件发送',recipients=['153531611@qq.com'],body='小伙子你好帅呀')
    mail.send(message)
    return 'successful'


@bp.route('/posts/')
@login_required
@permission_required(CMSPersmisson.POSTER)
def posts():
    context={
        'posts':PostModel.query.all()
    }
    return render_template('cms/cms_posts.html',**context)


@bp.route('/hpost/',methods=['POST'])
@login_required
@permission_required(CMSPersmisson.POSTER)
def hpost():
    post_id = request.form.get('post_id')
    if not post_id:
        return restful.params_error(message='请传入帖子id')
    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error('没有这篇帖子！')
    highlight = HighlightPostModel()
    highlight.post = post
    db.session.add(highlight)
    db.session.commit()
    return restful.success()


@bp.route('/uhpost/',methods=['POST'])
@login_required
@permission_required(CMSPersmisson.POSTER)
def uhpost():
    post_id = request.form.get('post_id')
    if not post_id:
        return restful.params_error(message='请传入帖子id')
    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error('没有这篇帖子！')
    highlight = HighlightPostModel.query.filter_by(post_id=post_id).first()
    db.session.delete(highlight)
    db.session.commit()
    return restful.success()


@bp.route('/dpost/',methods=['POST'])
@login_required
@permission_required(CMSPersmisson.POSTER)
def dpost():
    post_id = request.form.get('post_id')
    if not post_id:
        return restful.params_error(message='请传入帖子id')
    post = PostModel.query.filter_by(id=post_id).first()
    if not post:
        return restful.params_error('没有这篇帖子！')
    read_posts = ReadcountModel.query.filter_by(post_id=post_id).first()
    comment_posts = CommentModel.query.filter_by(post_id=post_id).all()
    if read_posts:
        db.session.delete(read_posts)
    if comment_posts:
        for comment_post in comment_posts:
            db.session.delete(comment_post)
    db.session.delete(post)
    db.session.commit()
    return restful.success()


@bp.route('/comments/')
@login_required
@permission_required(CMSPersmisson.COMMENTER)
def comments():
    return render_template('cms/cms_comments.html')


@bp.route('/boards/')
@login_required
@permission_required(CMSPersmisson.BOARDER)
def boards():
    board_models = BoardModel.query.all()
    posts = {}
    for board in board_models:
        posts[board.id] = len(PostModel.query.filter(PostModel.board_id == board.id).all())
    context = {
        'boards':board_models,
        'posts':posts
    }
    return render_template('cms/cms_boards.html',**context)


@bp.route('/fusers/')
@login_required
@permission_required(CMSPersmisson.FRONTUSER)
def fusers():
    return render_template('cms/cms_fusers.html')


@bp.route('/cusers/')
@login_required
@permission_required(CMSPersmisson.CMSUSER)
def cusers():
    return render_template('cms/cms_cusers.html')


@bp.route('/croles/')
@login_required
@permission_required(CMSPersmisson.ALL_PERMISSION)
def croles():
    return render_template('cms/cms_croles.html')


@bp.route('/cinterfaces/')
@login_required
@permission_required(CMSPersmisson.ALL_PERMISSION)
def cinterfaces():
    return render_template('cms/cms_interfaces.html')

@bp.route('/banners/')
@login_required
def banners():
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).all()
    return render_template('cms/cms_banners.html',banners=banners)


@bp.route('/abanner/',methods=['POST'])
@login_required
def abanner():
    form = AddBannerForm(request.form)
    if form.validate():
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel(name=name,image_url=image_url,link_url=link_url,priority=priority)
        db.session.add(banner)
        db.session.commit()
        return restful.success()

    else:
        return restful.params_error(message=form.get_error())


@bp.route('/ubanner/',methods=['POST'])
@login_required
def ubanner():
    form = UpdateBannerForm(request.form)
    if form.validate():
        banner_id = form.banner_id.data
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel.query.get(banner_id)
        if banner:
            banner.name = name
            banner.image_url = image_url
            banner.link_url = link_url
            banner.priority = priority
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message='没有这个轮播图！')


    else:
        return restful.params_error(message=form.get_error())


@bp.route('/dbanner/',methods=['POST'])
@login_required
def dbanner():
    banner_id = request.form.get('banner_id')
    if not banner_id:
        return restful.params_error(message='请传入轮播入id')
    banner = BannerModel.query.get(banner_id)
    if not banner:
        return restful.params_error(message='没有这个轮播图！')
    db.session.delete(banner)
    db.session.commit()
    return restful.success()

@bp.route('/aboard/',methods=['POST'])
@login_required
@permission_required(CMSPersmisson.BOARDER)
def aboard():
    form = AddBoardForm(request.form)
    if form.validate():
        name = form.name.data
        board = BoardModel(name=name)
        db.session.add(board)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/uboard/',methods=['POST'])
@login_required
@permission_required(CMSPersmisson.BOARDER)
def uboard():
    form = UpdateBoardForm(request.form)
    if form.validate():
        board_id = form.board_id.data
        name = form.name.data
        board = BoardModel.query.get(board_id)
        if board:
            board.name = name
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message='没有这个板块')
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/dboard/',methods=['POST'])
@login_required
@permission_required(CMSPersmisson.BOARDER)
def dboard():
    board_id = request.form.get('board_id')
    if not board_id:
        return restful.params_error(message='请传入板块id')
    board = BoardModel.query.get(board_id)
    if not board:
        return restful.params_error(message='没有这个板块！')
    db.session.delete(board)
    db.session.commit()
    return restful.success()


class LoginView(views.MethodView):
    def get(self,message = None):
        return render_template('cms/cms_login.html',message=message)

    def post(self):
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            user = CMSUser.query.filter_by(email=email).first()
            if user and user.check_password(password):
                session[config.CMS_USER_ID] = user.id
                if remember:
                    #如果设置session.permanent=True,那么过期时间是31天
                    session.permanent = True
                return redirect(url_for('cms.index'))
            else:
                return  self.get(message='邮箱或者密码错误')

        else:
            message = form.get_error()
            return self.get(message=message)

class ResetPwdView(views.MethodView):
    decorators = [login_required]
    def get(self):
        return render_template('cms/cms_resetpwd.html')
    def post(self):
        form = ResetpwdForm(request.form)
        if form.validate():
            oldpwd = form.oldpwd.data
            newpwd = form.newpwd.data
            user = g.cms_user
            if user.check_password(oldpwd):
                user.password = newpwd
                db.session.commit()
                return restful.success()
            else:
                return restful.params_error('旧密码错误！')
        else:
            return restful.params_error(form.get_error())

class ResetEmailView(views.MethodView):

    decorators = [login_required]

    def get(self):
        return render_template('cms/cms_resetemail.html')

    def post(self):

        form = ResetEmailForm(request.form)
        if form.validate():
            email = form.email.data

HET/templates/cms/cms_base.html
{% from 'common/_macros.html' import static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% include "common/_heads.html" %}
    <link rel="stylesheet" href="{{ static('cms/css/base.css') }}">
    <script src="{{ static('cms/js/base.js')}}"></script>

    {% block head %}{% endblock %}
</head>
<body>
     <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('cms.index') }}">和而泰论坛CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('cms.profile') }}">{{ g.cms_user.username }}</a></li>
            <li><a href="{{ url_for('cms.loginout') }}">注销</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="查找...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                        <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                        <li><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>
                    </ul>
                </li>

                  {% set cms_user = g.cms_user %}
                  <li class="nav-group banner-manage"><a href="{{ url_for('cms.banners') }}">轮播图管理</a></li>

                  {% if cms_user.has_permission(CMSPermission.POSTER) %}

                <li class="nav-group post-manage"><a href="{{ url_for('cms.posts') }}">帖子管理</a></li>
                  {% endif %}




              {% if cms_user.has_permission(CMSPermission.COMMENTER) %}

                <li class="comments-manage"><a href="{{ url_for('cms.comments') }}">评论管理</a></li>
                  {% endif %}
              {% if cms_user.has_permission(CMSPermission.BOARDER) %}

                <li class="board-manage"><a href="{{ url_for('cms.boards') }}">板块管理</a></li>
                  {% endif %}
              {% if cms_user.has_permission(CMSPermission.FRONTUSER) %}

                <li class="nav-group user-manage"><a href="{{ url_for('cms.fusers') }}">前台用户管理</a></li>
                  {% endif %}
              {% if cms_user.has_permission(CMSPermission.CMSUSER) %}

                <li class="nav-group cmsuser-manage"><a href="{{ url_for('cms.cusers') }}">CMS用户管理</a></li>
                  {% endif %}

              {% if cms_user.is_developer%}

                  <li class="cinterfaces-manage"><a href="{{ url_for('cms.cinterfaces') }}">het接口管理</a></li>

{#                <li class="cmsrole-manage"><a href="{{ url_for('cms.croles') }}">CMS组管理</a></li>#}
              {% endif %}

            </ul>
          </div>
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_title %}{% endblock %}</h1>
            <div class="main_content">
                {% block main_content %}{% endblock %}
            </div>
          </div>
      </div>
    </div>
</body>
</html>

HET/templates/cms/cms_boards.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}
{% block title %}
    板块管理
{% endblock %}

{% block head %}
    <script src="{{ static('cms/js/boards.js') }}"></script>
{% endblock %}

{% block page_title %}
{{ self.title() }}
{% endblock %}

{% block main_content %}
    <div class="top-box">
        <button class="btn btn-warning" style="float:right;" id="add-board-btn">添加新板块</button>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>板块名称</th>
                <th>拥有文章数量</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for board in boards %}
                <tr data-name="{{ board.name }}" data-id="{{ board.id }}">
                    <td>{{ board.name }}</td>
                    <td>{{ posts[board.id] }}</td>
                    <td>{{ board.create_time }}</td>
                    <td>
                        <button class="btn btn-default btn-xs edit-board-btn">编辑</button>
                        <button class="btn btn-danger btn-xs delete-board-btn">删除</button>
                    </td>
                </tr>
            
            {% endfor %}
            
        </tbody>
    </table>
{% endblock %}

HET/templates/cms/cms_posts.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}
{% block title %}
    帖子管理
{% endblock %}

{% block head %}
    <script src="{{ static('cms/js/posts.js') }}"></script>
{% endblock %}

{% block page_title %}
{{ self.title() }}
{% endblock %}

{% block main_content %}
    <table class="table table table-hover table-bordered">
        <thead>
            <tr>
                <th>标题</th>
                <th>发布时间</th>
                <th>板块</th>
                <th>作者</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
                <tr data-id="{{ post.id }}" data-highlight="{{ 1 if post.highlight else 0 }} " >
                    <td><a target="_blank" href="{{ url_for('front.post_detail',post_id=post.id) }}">{{ post.title }}</a></td>
                    <td>{{ post.create_time }}</td>
                    <td>{{ post.board.name }}</td>
                    <td>{{ post.author.username }}</td>
                    <td>
                        {% if post.highlight %}
                            <button class="btn btn-default btn-xs highlight-btn">取消加精</button>
                        {% else %}
                            <button class="btn btn-default btn-xs highlight-btn">加精</button>
                        {% endif %}
                            <button class="btn btn-danger btn-xs delete-btn">移除</button>

                    </td>
                </tr>
            
            {% endfor %}
            
        </tbody>
    </table>
{% endblock %}